@startuml
class es.ull.patrones.practica7.Connection.FreePortFinder {
+ {static} int findFreePort(int)
+ {static} boolean isPortAvailable(int)
}
class es.ull.patrones.practica7.Connection.ReadJsonFromUrl {
+ {static} JsonNode read(String)
- {static} String readJsonFromUrl(String)
}
class es.ull.patrones.practica7.Connection.APIConnection {
+ {static} String getFlightId(String,String)
+ {static} String loadConnection(String,String,String)
}
@enduml